import React, { createContext, useState, useContext, useEffect, type ReactNode } from 'react';

// Define verification status
export interface VerificationStatus {
  isProfileComplete: boolean;
  isEmailVerified: boolean;
  isPhoneVerified: boolean;
  isIdVerified: boolean;
  isAddressVerified: boolean;
  isFullyVerified: boolean;
  verificationStep: 'profile' | 'email' | 'phone' | 'id' | 'address' | 'complete';
}

// Define user type
export interface User {
  id: string;
  name: string;
  email: string;
  avatar?: string;
  phone?: string;
  dateOfBirth?: string;
  address?: {
    street: string;
    city: string;
    state: string;
    country: string;
    zipCode: string;
  };
  verification: VerificationStatus;
  joinedDate: string;
}

// Define context type
interface AuthContextType {
  user: User | null;
  isAuthenticated: boolean;
  isLoading: boolean;
  login: (email: string, password: string) => Promise<boolean>;
  register: (name: string, email: string, password: string) => Promise<boolean>;
  logout: () => void;
  updateUser: (updates: Partial<User>) => void;
  updateVerificationStatus: (updates: Partial<VerificationStatus>) => void;
  canListItems: () => boolean;
  canRentItems: () => boolean;
  error: string | null;
}

// Create the auth context with default values
const AuthContext = createContext<AuthContextType>({
  user: null,
  isAuthenticated: false,
  isLoading: true,
  login: async () => false,
  register: async () => false,
  logout: () => {},
  updateUser: () => {},
  updateVerificationStatus: () => {},
  canListItems: () => false,
  canRentItems: () => false,
  error: null,
});

// Custom hook to use the auth context
export const useAuth = () => useContext(AuthContext);

interface AuthProviderProps {
  children: ReactNode;
}

export const AuthProvider: React.FC<AuthProviderProps> = ({ children }) => {
  const [user, setUser] = useState<User | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  // Check for existing user session on initial load
  useEffect(() => {
    const checkAuthStatus = async () => {
      try {
        // In a real application, you would verify the token with your backend
        const storedUser = localStorage.getItem('user');
        
        if (storedUser) {
          const parsedUser = JSON.parse(storedUser);
          setUser(parsedUser);
        }
      } catch (error) {
        console.error('Authentication error:', error);
        localStorage.removeItem('user');
      } finally {
        setIsLoading(false);
      }
    };

    checkAuthStatus();
  }, []);

  // Mock login function
  const login = async (email: string, password: string): Promise<boolean> => {
    setIsLoading(true);
    setError(null);
    
    try {
      // This is a mock implementation
      // In a real app, you would call your API
      await new Promise(resolve => setTimeout(resolve, 1000)); // Simulate API call
      
      // Simple validation
      if (email === 'user@example.com' && password === 'password') {
        const mockUser: User = {
          id: '1',
          name: 'John Smith',
          email: 'user@example.com',
          avatar: '/assets/img/profiles/avatar-01.jpg',
          verification: {
            isProfileComplete: false,
            isEmailVerified: false,
            isPhoneVerified: false,
            isIdVerified: false,
            isAddressVerified: false,
            isFullyVerified: false,
            verificationStep: 'profile'
          },
          joinedDate: new Date().toISOString()
        };
        
        localStorage.setItem('user', JSON.stringify(mockUser));
        setUser(mockUser);
        return true;
      }
      
      setError('Invalid email or password');
      return false;
    } catch (err) {
      setError('An error occurred during login. Please try again.');
      return false;
    } finally {
      setIsLoading(false);
    }
  };

  // Mock register function
  const register = async (name: string, email: string, password: string): Promise<boolean> => {
    setIsLoading(true);
    setError(null);
    
    try {
      // This is a mock implementation
      // In a real app, you would call your API
      await new Promise(resolve => setTimeout(resolve, 1000)); // Simulate API call
      
      // Simple validation
      if (email && password && name) {
        const mockUser: User = {
          id: '2', // In a real app, this would be generated by the backend
          name,
          email,
          avatar: '/assets/img/profiles/avatar-02.jpg', // Default avatar
          verification: {
            isProfileComplete: false,
            isEmailVerified: false,
            isPhoneVerified: false,
            isIdVerified: false,
            isAddressVerified: false,
            isFullyVerified: false,
            verificationStep: 'profile'
          },
          joinedDate: new Date().toISOString()
        };
        
        localStorage.setItem('user', JSON.stringify(mockUser));
        setUser(mockUser);
        return true;
      }
      
      setError('All fields are required');
      return false;
    } catch (err) {
      setError('An error occurred during registration. Please try again.');
      return false;
    } finally {
      setIsLoading(false);
    }
  };

  // Logout function
  const logout = () => {
    localStorage.removeItem('user');
    setUser(null);
  };

  // Update user function
  const updateUser = (updates: Partial<User>) => {
    if (user) {
      const updatedUser = { ...user, ...updates };
      setUser(updatedUser);
      localStorage.setItem('user', JSON.stringify(updatedUser));
    }
  };

  // Update verification status function
  const updateVerificationStatus = (updates: Partial<VerificationStatus>) => {
    if (user) {
      const updatedVerification = { ...user.verification, ...updates };
      
      // Auto-calculate isFullyVerified based on individual verification states
      const isFullyVerified = 
        updatedVerification.isProfileComplete &&
        updatedVerification.isEmailVerified &&
        updatedVerification.isPhoneVerified &&
        updatedVerification.isIdVerified &&
        updatedVerification.isAddressVerified;

      updatedVerification.isFullyVerified = isFullyVerified;
      
      // Update verification step based on completion
      if (isFullyVerified) {
        updatedVerification.verificationStep = 'complete';
      } else if (!updatedVerification.isProfileComplete) {
        updatedVerification.verificationStep = 'profile';
      } else if (!updatedVerification.isEmailVerified) {
        updatedVerification.verificationStep = 'email';
      } else if (!updatedVerification.isPhoneVerified) {
        updatedVerification.verificationStep = 'phone';
      } else if (!updatedVerification.isIdVerified) {
        updatedVerification.verificationStep = 'id';
      } else if (!updatedVerification.isAddressVerified) {
        updatedVerification.verificationStep = 'address';
      }

      updateUser({ verification: updatedVerification });
    }
  };

  // Check if user can list items (requires full verification)
  const canListItems = (): boolean => {
    return user?.verification.isFullyVerified || false;
  };

  // Check if user can rent items (requires basic verification: profile + email)
  const canRentItems = (): boolean => {
    if (!user) return false;
    return user.verification.isProfileComplete && user.verification.isEmailVerified;
  };

  const value = {
    user,
    isAuthenticated: !!user,
    isLoading,
    login,
    register,
    logout,
    updateUser,
    updateVerificationStatus,
    canListItems,
    canRentItems,
    error,
  };

  return <AuthContext.Provider value={value}>{children}</AuthContext.Provider>;
};
